// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm7GeRq2KoB5TNnCQwqrXB7CnRPv4yaZk',
    appId: '1:831592746122:web:952bc0215cc93595ff7173',
    messagingSenderId: '831592746122',
    projectId: 'postsapp-ce9dc',
    authDomain: 'postsapp-ce9dc.firebaseapp.com',
    storageBucket: 'postsapp-ce9dc.firebasestorage.app',
    measurementId: 'G-G6MXVDPZT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw-aeDbIjml0mqMzarSyzfpZTw0I_UM8o',
    appId: '1:831592746122:android:6f13d957bbb84047ff7173',
    messagingSenderId: '831592746122',
    projectId: 'postsapp-ce9dc',
    storageBucket: 'postsapp-ce9dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbokItS0bGOulei-43jCnSI-5cVO7590A',
    appId: '1:831592746122:ios:49cb2a9175f9bd9aff7173',
    messagingSenderId: '831592746122',
    projectId: 'postsapp-ce9dc',
    storageBucket: 'postsapp-ce9dc.firebasestorage.app',
    iosBundleId: 'com.example.testPack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbokItS0bGOulei-43jCnSI-5cVO7590A',
    appId: '1:831592746122:ios:49cb2a9175f9bd9aff7173',
    messagingSenderId: '831592746122',
    projectId: 'postsapp-ce9dc',
    storageBucket: 'postsapp-ce9dc.firebasestorage.app',
    iosBundleId: 'com.example.testPack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm7GeRq2KoB5TNnCQwqrXB7CnRPv4yaZk',
    appId: '1:831592746122:web:2689552fd417e41dff7173',
    messagingSenderId: '831592746122',
    projectId: 'postsapp-ce9dc',
    authDomain: 'postsapp-ce9dc.firebaseapp.com',
    storageBucket: 'postsapp-ce9dc.firebasestorage.app',
    measurementId: 'G-9D9178BM67',
  );
}
